<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb65826e46126011363541eaf02bfed37
{
    public static $prefixLengthsPsr4 = array (
        'S' =>
        array (
            'Symfony\\Component\\Process\\' => 26,
        ),
        'O' =>
        array (
            'OCA\\NCExtrak\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\Process\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'OCA\\NCExtrak\\' =>
        array (
            0 => __DIR__ . '/../..' . '/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OCA\\NCExtrak\\AppInfo\\Application' => __DIR__ . '/../..' . '/lib/AppInfo/Application.php',
        'OCA\\NCExtrak\\BackgroundJob\\ExtractJob' => __DIR__ . '/../..' . '/lib/BackgroundJob/ExtractJob.php',
        'OCA\\NCExtrak\\Controller\\ExtractController' => __DIR__ . '/../..' . '/lib/Controller/ExtractController.php',
        'OCA\\NCExtrak\\Db\\Job' => __DIR__ . '/../..' . '/lib/Db/Job.php',
        'OCA\\NCExtrak\\Db\\JobMapper' => __DIR__ . '/../..' . '/lib/Db/JobMapper.php',
        'OCA\\NCExtrak\\Dto\\ExtractOptions' => __DIR__ . '/../..' . '/lib/Dto/ExtractOptions.php',
        'OCA\\NCExtrak\\Dto\\ExtractResult' => __DIR__ . '/../..' . '/lib/Dto/ExtractResult.php',
        'OCA\\NCExtrak\\Exception\\ArchiveTooLargeException' => __DIR__ . '/../..' . '/lib/Exception/ArchiveTooLargeException.php',
        'OCA\\NCExtrak\\Exception\\ExtractionException' => __DIR__ . '/../..' . '/lib/Exception/ExtractionException.php',
        'OCA\\NCExtrak\\Exception\\UnsupportedFormatException' => __DIR__ . '/../..' . '/lib/Exception/UnsupportedFormatException.php',
        'OCA\\NCExtrak\\Extractor\\ExtractorInterface' => __DIR__ . '/../..' . '/lib/Extractor/ExtractorInterface.php',
        'OCA\\NCExtrak\\Extractor\\RarExtractor' => __DIR__ . '/../..' . '/lib/Extractor/RarExtractor.php',
        'OCA\\NCExtrak\\Extractor\\SafePath' => __DIR__ . '/../..' . '/lib/Extractor/SafePath.php',
        'OCA\\NCExtrak\\Extractor\\SevenZipExtractor' => __DIR__ . '/../..' . '/lib/Extractor/SevenZipExtractor.php',
        'OCA\\NCExtrak\\Extractor\\TarExtractor' => __DIR__ . '/../..' . '/lib/Extractor/TarExtractor.php',
        'OCA\\NCExtrak\\Extractor\\ZipExtractor' => __DIR__ . '/../..' . '/lib/Extractor/ZipExtractor.php',
        'OCA\\NCExtrak\\Listener\\LoadAdditionalScriptsListener' => __DIR__ . '/../..' . '/lib/Listener/LoadAdditionalScriptsListener.php',
        'OCA\\NCExtrak\\Migration\\Version000001Date20260510073000' => __DIR__ . '/../..' . '/lib/Migration/Version000001Date20260510073000.php',
        'OCA\\NCExtrak\\Notification\\NotificationService' => __DIR__ . '/../..' . '/lib/Notification/NotificationService.php',
        'OCA\\NCExtrak\\Notification\\Notifier' => __DIR__ . '/../..' . '/lib/Notification/Notifier.php',
        'OCA\\NCExtrak\\Service\\ArchiveDetector' => __DIR__ . '/../..' . '/lib/Service/ArchiveDetector.php',
        'OCA\\NCExtrak\\Service\\ExtractOptionsFactory' => __DIR__ . '/../..' . '/lib/Service/ExtractOptionsFactory.php',
        'OCA\\NCExtrak\\Service\\ExtractionService' => __DIR__ . '/../..' . '/lib/Service/ExtractionService.php',
        'OCA\\NCExtrak\\Service\\ExtractorRegistry' => __DIR__ . '/../..' . '/lib/Service/ExtractorRegistry.php',
        'Symfony\\Component\\Process\\Exception\\ExceptionInterface' => __DIR__ . '/..' . '/symfony/process/Exception/ExceptionInterface.php',
        'Symfony\\Component\\Process\\Exception\\InvalidArgumentException' => __DIR__ . '/..' . '/symfony/process/Exception/InvalidArgumentException.php',
        'Symfony\\Component\\Process\\Exception\\LogicException' => __DIR__ . '/..' . '/symfony/process/Exception/LogicException.php',
        'Symfony\\Component\\Process\\Exception\\ProcessFailedException' => __DIR__ . '/..' . '/symfony/process/Exception/ProcessFailedException.php',
        'Symfony\\Component\\Process\\Exception\\ProcessSignaledException' => __DIR__ . '/..' . '/symfony/process/Exception/ProcessSignaledException.php',
        'Symfony\\Component\\Process\\Exception\\ProcessStartFailedException' => __DIR__ . '/..' . '/symfony/process/Exception/ProcessStartFailedException.php',
        'Symfony\\Component\\Process\\Exception\\ProcessTimedOutException' => __DIR__ . '/..' . '/symfony/process/Exception/ProcessTimedOutException.php',
        'Symfony\\Component\\Process\\Exception\\RunProcessFailedException' => __DIR__ . '/..' . '/symfony/process/Exception/RunProcessFailedException.php',
        'Symfony\\Component\\Process\\Exception\\RuntimeException' => __DIR__ . '/..' . '/symfony/process/Exception/RuntimeException.php',
        'Symfony\\Component\\Process\\ExecutableFinder' => __DIR__ . '/..' . '/symfony/process/ExecutableFinder.php',
        'Symfony\\Component\\Process\\InputStream' => __DIR__ . '/..' . '/symfony/process/InputStream.php',
        'Symfony\\Component\\Process\\Messenger\\RunProcessContext' => __DIR__ . '/..' . '/symfony/process/Messenger/RunProcessContext.php',
        'Symfony\\Component\\Process\\Messenger\\RunProcessMessage' => __DIR__ . '/..' . '/symfony/process/Messenger/RunProcessMessage.php',
        'Symfony\\Component\\Process\\Messenger\\RunProcessMessageHandler' => __DIR__ . '/..' . '/symfony/process/Messenger/RunProcessMessageHandler.php',
        'Symfony\\Component\\Process\\PhpExecutableFinder' => __DIR__ . '/..' . '/symfony/process/PhpExecutableFinder.php',
        'Symfony\\Component\\Process\\PhpProcess' => __DIR__ . '/..' . '/symfony/process/PhpProcess.php',
        'Symfony\\Component\\Process\\PhpSubprocess' => __DIR__ . '/..' . '/symfony/process/PhpSubprocess.php',
        'Symfony\\Component\\Process\\Pipes\\AbstractPipes' => __DIR__ . '/..' . '/symfony/process/Pipes/AbstractPipes.php',
        'Symfony\\Component\\Process\\Pipes\\PipesInterface' => __DIR__ . '/..' . '/symfony/process/Pipes/PipesInterface.php',
        'Symfony\\Component\\Process\\Pipes\\UnixPipes' => __DIR__ . '/..' . '/symfony/process/Pipes/UnixPipes.php',
        'Symfony\\Component\\Process\\Pipes\\WindowsPipes' => __DIR__ . '/..' . '/symfony/process/Pipes/WindowsPipes.php',
        'Symfony\\Component\\Process\\Process' => __DIR__ . '/..' . '/symfony/process/Process.php',
        'Symfony\\Component\\Process\\ProcessUtils' => __DIR__ . '/..' . '/symfony/process/ProcessUtils.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb65826e46126011363541eaf02bfed37::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb65826e46126011363541eaf02bfed37::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb65826e46126011363541eaf02bfed37::$classMap;

        }, null, ClassLoader::class);
    }
}
